DROP TABLE IF EXISTS PHOTOS;

CREATE TABLE PHOTOS (
  ID      INT NOT NULL AUTO_INCREMENT,
  PHOTO   BLOB,
  VERSION INT NOT NULL DEFAULT 0,
  PRIMARY KEY (ID)
);


DROP TABLE IF EXISTS CONTACTS;

CREATE TABLE CONTACTS (
  ID          INT         NOT NULL AUTO_INCREMENT,
  FIRST_NAME  VARCHAR(60) NOT NULL,
  LAST_NAME   VARCHAR(40) NOT NULL,
  BIRTH_DATE  DATE,
  DESCRIPTION VARCHAR(2000),
  PHOTO_ID    INT,
  VERSION     INT         NOT NULL DEFAULT 0,
  UNIQUE UQ_CONTACT_1 (FIRST_NAME, LAST_NAME),
  PRIMARY KEY (ID),
  FOREIGN KEY (PHOTO_ID) REFERENCES PHOTOS (ID)
);



